project:
  type: website
  output-dir: docs

website:
  title: "quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: labs.qmd 
        text: labs
      - href: resources.qmd
        text: rescources

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



